version: "3.8"

services:
  api:
    image: ghcr.io/luanlum/projeto-contabilidade:latest
    container_name: backend-api
    restart: always
    ports:
      - "3001:3001"
    deploy:
      resources:
        limits:
          memory: 512M
    env_file:
      - .env
