// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
  migrate: {
    // Usa a URL direta (porta 5432) para conseguir criar as tabelas
    databaseUrl: process.env.DIRECT_URL,
  },
});
